language: go

go:
  - master

install:
  - go get github.com/spf13/hugo

script:
  - hugo # This commands builds your website on travis

deploy:
  local_dir: public
  repo: echovap/web # This is the slug of the repo you want to deploy your site to
  target_branch: master # GitHub pages branch to deploy to (in other cases it can be gh-pages)
  provider: pages
  fqdn: echovap.com
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # This is the authentication which you will setup in the next step in travis-ci dashboard
  email: carlosvega20@mail.com
  name: "carlosvega20"
  on:
    branch: master